# Generated by Django 4.1.7 on 2023-07-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='order',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='paragraph',
            field=models.TextField(default='', max_length=250),
        ),
    ]
