# Generated by Django 4.2.3 on 2023-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contuctus',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contuctus',
            name='sub_title',
            field=models.TextField(max_length=250),
        ),
    ]
