# Generated by Django 4.1.7 on 2023-07-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contuctus_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContuctForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Contuct form',
                'verbose_name_plural': 'Contuct form',
            },
        ),
        migrations.AlterModelOptions(
            name='contuctus',
            options={'verbose_name': 'Contuct Us', 'verbose_name_plural': 'Contuct Us'},
        ),
    ]
