# Generated by Django 4.2.3 on 2023-07-29 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('title_highlighted', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('btn', models.TextField(max_length=250)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='ProjectsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('number', models.DecimalField(decimal_places=0, default='', max_digits=10)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Projects Value',
                'verbose_name_plural': 'Projects Value',
            },
        ),
        migrations.CreateModel(
            name='ProjectsPayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('number', models.DecimalField(decimal_places=0, default='', max_digits=10)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Projects Payback',
                'verbose_name_plural': 'Projects Payback',
            },
        ),
        migrations.CreateModel(
            name='ProjectsGrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('number', models.DecimalField(decimal_places=0, default='', max_digits=10)),
                ('description', models.TextField(max_length=250)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Projects Growing',
                'verbose_name_plural': 'Projects Growing',
            },
        ),
        migrations.CreateModel(
            name='ProjectsExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('number', models.DecimalField(decimal_places=0, default='', max_digits=10)),
                ('description', models.TextField(max_length=250)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Projects Experience',
                'verbose_name_plural': 'Projects Experience',
            },
        ),
        migrations.CreateModel(
            name='ProjectsArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('number', models.DecimalField(decimal_places=0, default='', max_digits=10)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Projects Area',
                'verbose_name_plural': 'Projects Area',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('title_highlighted', models.TextField(max_length=250)),
                ('btn', models.TextField(max_length=250)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_contant', models.TextField(max_length=250)),
                ('hero_video_or_image', models.FileField(upload_to='documents/')),
                ('order', models.DecimalField(decimal_places=0, default='', max_digits=10)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Slider',
            },
        ),
        migrations.CreateModel(
            name='CreateValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Create Value',
                'verbose_name_plural': 'Create Value',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('title_highlighted', models.TextField(max_length=250)),
                ('logo', models.ImageField(upload_to='documents/')),
                ('btn', models.TextField(max_length=250)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('content', models.TextField(max_length=250)),
                ('photo', models.ImageField(upload_to='documents/')),
                ('btn', models.TextField(max_length=250)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hero')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
    ]
