# Generated by Django 4.1.7 on 2023-07-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(upload_to='documents/')),
                ('certificate_pdf', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificate',
            },
        ),
    ]
