# Generated by Django 4.1.7 on 2023-07-22 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_alter_certificate_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_pdf',
            new_name='pdf',
        ),
    ]
